### ISSUE TITLE
How do you plan on implementing the miner?

### ISSUE THREAD

**Issue by SaturnsVoid** [seantcanavan/anon-eth-net#10]
Kinda interested on how you plan to implement the miner? Are you going to have the program download a miner and run it with parameters or...?

**Comment by seantcanavan** [comment]
your choice of miner based on your platform will be very easy to select. the 'loader' module will execute arbitrary external processes, capture their log output, and restart them when they exit.

additionally, the logger will soon have the ability to email out logs regularly as well as email them out as a form of backup when the logs begin to pile up too far.

i hope to have a mining example within the code base in the next week or two. for now the functionality is easily integrateable into the code yourself.

for future releases you'll even be able to use REST to manually capture logs, start, restart, and install new processes remotely for the program to execute.
